# Generated by Django 5.2.8 on 2026-04-12 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='date_of_registration',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
