# Generated by Django 5.2.8 on 2026-04-16 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_teacherinfo_date_of_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningAreaMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20)),
                ('stream', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=20)),
                ('year', models.IntegerField(default=2026)),
                ('exam_type', models.CharField(choices=[('Opener', 'Opener'), ('Mid Term', 'Mid Term'), ('End Term', 'End Term')], max_length=20)),
                ('marks', models.FloatField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='core.learningarea')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_area_marks', to='core.masterschool')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_area_marks', to='core.studentinfo')),
            ],
            options={
                'db_table': 'learning_area_marks',
                'unique_together': {('student', 'learning_area', 'term', 'year', 'exam_type')},
            },
        ),
    ]
