# Generated by Django 5.2.8 on 2026-04-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_learningareamark'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningareamark',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
