# Generated by Django 5.2.8 on 2026-04-16 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_announcement_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('Admin', 'School Admin')], max_length=20)),
                ('location', models.CharField(help_text='e.g. Nairobi, Kenya', max_length=100)),
                ('content', models.TextField(verbose_name='Review Message')),
                ('rating', models.IntegerField(default=5)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.masterschool')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
